services:
  sql-app:
    build:
      context: . 
      dockerfile: Dockerfile
      args:
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_EMAIL: ${GIT_EMAIL}
    container_name: projetos_sql
    volumes:
      - .:/usr/src/app
      - ./collection-archive-sql:/usr/src/app/collection-archive-sql
    working_dir: /usr/src/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: tail -f /dev/null

  mysql:
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
      - ./collection-archive-sql/06_shinsengumi/sql-scripts:/docker-entrypoint-initdb.d
    ports:
      - "2004:3306"

networks:
  default:
    driver: bridge
