services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "2004:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network

volumes:
  mysql_data:

networks:
  db_network:
